language: generic
dist: trusty
sudo: false

os:
  - linux
  - osx

env:
  matrix:
    - PYTHON_VERSION=2.7
    - PYTHON_VERSION=3.5
    - PYTHON_VERSION=3.6
  global:
    - MINCONDA_VERSION="latest"
    - MINCONDA_LINUX="Linux-x86_64"
    - MINCONDA_OSX="MacOSX-x86_64"

addons:
  apt:
    packages:
      - libblas-dev
      - liblapack-dev
      - gfortran

before_install:
  - if [[ "$PYTHON_VERSION" == "2.7" ]]; then
      MINCONDA_PYTHON_VERSION=2;
    else
      MINCONDA_PYTHON_VERSION=3;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      MINCONDA_OS=$MINCONDA_LINUX;
      sudo apt-get update;
    elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      MINCONDA_OS=$MINCONDA_OSX;
      brew update;
    fi
  - wget "http://repo.continuum.io/miniconda/Miniconda$MINCONDA_PYTHON_VERSION-$MINCONDA_VERSION-$MINCONDA_OS.sh" -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes
  - conda update -q conda
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      conda install python.app;
    fi
  - conda create -q -n test-environment python=$PYTHON_VERSION pip numpy matplotlib
  - source activate test-environment
  - "pip install -q pytest"
  - "pip install -q coverage"
  - "pip install -r requirements.txt"
  - "conda list" # Show the package versions (for debugging)

install:
  - "pip install ."

script:
  - "coverage run --source=libtlda -m pytest"

after_script:
  - "pip install scrutinizer-ocular"
  - "ocular"

