name: libTLDA
channels:
- conda-forge
- defaults
dependencies:
- numpy>=1.12.1
- matplotlib>=2.0.2
- ipython>=5.5.0
- scipy>=0.11
- scikit-learn>=0.15.0
- Keras>=2.0.0
- tensorflow>=0.12.1
